### ISSUE TITLE
Would you make a common function to update score and show wrong answer message?

### ISSUE THREAD

**Issue by baramjin92** [yiyeon0914/TestPython#2]
https://github.com/yiyeon0914/TestPython/blame/3367dbf3155d988fa65a3857a5f54823a9092f02/Test.py#L9

You use these statements 3 times.
if ...
  score += 1
  print('correct')
else :
  print('wrong anser') 

Yon can define one function as follows.

def update_score(is_correct) :
   if is_correct == True : 
     score +=1 
     ...
   else :
     print('...')

and you can call this function per every answer. would you change the code with function?

**Comment by yiyeon0914** [comment]
Updated it so that the code you gave me works for my code
