### ISSUE TITLE
replace this code with call api

### ISSUE THREAD

**Issue by baramjin92** [yiyeon0914/TestPython#4]
https://github.com/yiyeon0914/TestPython/blob/b51edcef2d40274d848b5eb0702ce4f160f7e160/Test.py#L15

Current
    if answer.lower()=='samsung':
        score += 1
        print('correct')
    else:
        print('Wrong Answer :(')

New code 
    update_score(answer.lower() == 'samsung')

The other questions are same.

**Comment by yiyeon0914** [comment]
Corrected
